# Generated by Django 4.2.5 on 2024-04-01 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lanche',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_oferecido', models.CharField(max_length=255)),
                ('preçodoproduto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_vendedor', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('contato', models.CharField(max_length=20)),
            ],
        ),
    ]
