# Generated by Django 5.0.6 on 2024-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(max_length=255)),
                ('endereco_cliente', models.CharField(max_length=312)),
                ('contato_cliente', models.CharField(max_length=14)),
            ],
        ),
    ]
