# Generated by Django 5.0.6 on 2024-07-04 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='foto_produto',
            field=models.URLField(default='http://example.com', max_length=255),
        ),
    ]
