# Generated by Django 5.0.6 on 2024-06-10 18:14

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_cliente_cpf_alter_cliente_contato_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id_produto', models.AutoField(primary_key=True, serialize=False)),
                ('nome_produto', models.CharField(max_length=255)),
                ('preco_produto', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('descricao_produto', models.TextField()),
                ('categoria', models.CharField(max_length=255)),
                ('status_produto', models.CharField(max_length=255)),
                ('foto_produto', models.ImageField(blank=True, null=True, upload_to=api.models.upload_foto_produto)),
            ],
        ),
        migrations.DeleteModel(
            name='Lanche',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='contato',
        ),
        migrations.RemoveField(
            model_name='vendedor',
            name='email',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='cpf_cnpj_vendedor',
            field=models.CharField(default='00000000000', max_length=20),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='email_vendedor',
            field=models.CharField(default='email@example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='link_contato',
            field=models.URLField(default='http://example.com', max_length=255),
        ),
        migrations.AddField(
            model_name='vendedor',
            name='telefone_vendedor',
            field=models.CharField(default='0000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf',
            field=models.CharField(max_length=11),
        ),
    ]
