# Generated by Django 5.0.6 on 2024-06-11 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_produto_delete_lanche_remove_vendedor_contato_and_more'),
        ('api', '0004_remove_cliente_endereco_cliente_cliente_email_and_more'),
    ]

    operations = [
    ]
